# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

from cryptography.hazmat.primitives.asymmetric import dsa
from cryptography.hazmat.primitives import hashes

# Generate a DSA private key
private_key = dsa.generate_private_key(key_size=2048)

# Sign a message
message = b"My secure message"
signature = private_key.sign(
    message,
    hashes.SHA256()
)

# Verify the signature
public_key = private_key.public_key()
try:
    public_key.verify(signature, message, hashes.SHA256())
    print("Signature is valid ✅")
except Exception as e:
    print("Signature verification failed ❌:", e)

############################################3
Signature is valid ✅

